/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrolRouteImport } from './routes/enrol'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsVaultRouteImport } from './routes/_app.settings.vault'
import { Route as AppMMailboxRouteImport } from './routes/_app.m.$mailbox'
import { Route as AppMMailboxIndexRouteImport } from './routes/_app.m.$mailbox.index'
import { Route as AppSettingsAAddressRouteImport } from './routes/_app.settings.a.$address'
import { Route as AppMMailboxTSplatRouteImport } from './routes/_app.m.$mailbox.t.$'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolRoute = EnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsVaultRoute = AppSettingsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppMMailboxRoute = AppMMailboxRouteImport.update({
  id: '/m/$mailbox',
  path: '/m/$mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMMailboxIndexRoute = AppMMailboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMMailboxRoute,
} as any)
const AppSettingsAAddressRoute = AppSettingsAAddressRouteImport.update({
  id: '/a/$address',
  path: '/a/$address',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppMMailboxTSplatRoute = AppMMailboxTSplatRouteImport.update({
  id: '/t/$',
  path: '/t/$',
  getParentRoute: () => AppMMailboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enrol': typeof EnrolRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/connect': typeof AppConnectRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/m/$mailbox': typeof AppMMailboxRouteWithChildren
  '/settings/vault': typeof AppSettingsVaultRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/settings/a/$address': typeof AppSettingsAAddressRoute
  '/m/$mailbox/': typeof AppMMailboxIndexRoute
  '/m/$mailbox/t/$': typeof AppMMailboxTSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enrol': typeof EnrolRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/connect': typeof AppConnectRoute
  '/settings/vault': typeof AppSettingsVaultRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/a/$address': typeof AppSettingsAAddressRoute
  '/m/$mailbox': typeof AppMMailboxIndexRoute
  '/m/$mailbox/t/$': typeof AppMMailboxTSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/enrol': typeof EnrolRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/m/$mailbox': typeof AppMMailboxRouteWithChildren
  '/_app/settings/vault': typeof AppSettingsVaultRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/a/$address': typeof AppSettingsAAddressRoute
  '/_app/m/$mailbox/': typeof AppMMailboxIndexRoute
  '/_app/m/$mailbox/t/$': typeof AppMMailboxTSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enrol'
    | '/login'
    | '/welcome'
    | '/connect'
    | '/settings'
    | '/m/$mailbox'
    | '/settings/vault'
    | '/settings/'
    | '/settings/a/$address'
    | '/m/$mailbox/'
    | '/m/$mailbox/t/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enrol'
    | '/login'
    | '/welcome'
    | '/connect'
    | '/settings/vault'
    | '/settings'
    | '/settings/a/$address'
    | '/m/$mailbox'
    | '/m/$mailbox/t/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/enrol'
    | '/login'
    | '/welcome'
    | '/_app/connect'
    | '/_app/settings'
    | '/_app/m/$mailbox'
    | '/_app/settings/vault'
    | '/_app/settings/'
    | '/_app/settings/a/$address'
    | '/_app/m/$mailbox/'
    | '/_app/m/$mailbox/t/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EnrolRoute: typeof EnrolRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrol': {
      id: '/enrol'
      path: '/enrol'
      fullPath: '/enrol'
      preLoaderRoute: typeof EnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/vault': {
      id: '/_app/settings/vault'
      path: '/vault'
      fullPath: '/settings/vault'
      preLoaderRoute: typeof AppSettingsVaultRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/m/$mailbox': {
      id: '/_app/m/$mailbox'
      path: '/m/$mailbox'
      fullPath: '/m/$mailbox'
      preLoaderRoute: typeof AppMMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/m/$mailbox/': {
      id: '/_app/m/$mailbox/'
      path: '/'
      fullPath: '/m/$mailbox/'
      preLoaderRoute: typeof AppMMailboxIndexRouteImport
      parentRoute: typeof AppMMailboxRoute
    }
    '/_app/settings/a/$address': {
      id: '/_app/settings/a/$address'
      path: '/a/$address'
      fullPath: '/settings/a/$address'
      preLoaderRoute: typeof AppSettingsAAddressRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/m/$mailbox/t/$': {
      id: '/_app/m/$mailbox/t/$'
      path: '/t/$'
      fullPath: '/m/$mailbox/t/$'
      preLoaderRoute: typeof AppMMailboxTSplatRouteImport
      parentRoute: typeof AppMMailboxRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsVaultRoute: typeof AppSettingsVaultRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsAAddressRoute: typeof AppSettingsAAddressRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsVaultRoute: AppSettingsVaultRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsAAddressRoute: AppSettingsAAddressRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppMMailboxRouteChildren {
  AppMMailboxIndexRoute: typeof AppMMailboxIndexRoute
  AppMMailboxTSplatRoute: typeof AppMMailboxTSplatRoute
}

const AppMMailboxRouteChildren: AppMMailboxRouteChildren = {
  AppMMailboxIndexRoute: AppMMailboxIndexRoute,
  AppMMailboxTSplatRoute: AppMMailboxTSplatRoute,
}

const AppMMailboxRouteWithChildren = AppMMailboxRoute._addFileChildren(
  AppMMailboxRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppMMailboxRoute: typeof AppMMailboxRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppMMailboxRoute: AppMMailboxRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EnrolRoute: EnrolRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
