/**
 * `cacert.pem` decides which roots ship (NSS filtered to server auth); `certdata.txt` decides what each
 * may still vouch for. The output is committed so a trust change arrives as a diff.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { derFromPem } from '../harness/pem.ts';
// Not from `../src/index.ts`, which re-exports the artifact this script writes.
import { indexAnchors } from '../src/anchors.ts';
import { certificateDerKeys, derKey, serverDistrustByCertificate } from './certdata.ts';
import {
  CACERT_CACHE,
  CACERT_SHA256,
  CERTDATA_CACHE,
  CERTDATA_COMMIT,
  CERTDATA_SHA256,
} from './pin.ts';

const ARTIFACT = new URL('../src/root-bundle-generated.ts', import.meta.url).pathname;

/** Hashes of what is compiled, not what `anchors:fetch` verified on an earlier run: `.anchors/` is a cache. */
const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

const readVerified = (name: string, cache: string, expected: string): string => {
  const bytes = readFileSync(cache);
  const actual = sha256(bytes);
  if (actual !== expected) {
    throw new Error(
      `${name} in .anchors/ is not what pin.ts names.\n  pinned ${expected}\n  cached ${actual}\n` +
        'Run `pnpm -F @yozz.app/x509 anchors:fetch` — and if the pin was just bumped, read what\n' +
        'moved before trusting the result. Compiling the cached bytes under the new pin would\n' +
        'stamp the artifact with hashes it does not match.',
    );
  }
  return bytes.toString('utf8');
};

const cacert = readVerified('cacert.pem', CACERT_CACHE, CACERT_SHA256);
const certdata = readVerified('certdata.txt', CERTDATA_CACHE, CERTDATA_SHA256);

const bundle = derFromPem(cacert);
if (bundle.length === 0) throw new Error('cacert.pem yielded no certificates');

const distrust = serverDistrustByCertificate(certdata);
const known = certificateDerKeys(certdata);

/** A bundle root certdata has never heard of means the two pins are out of step; its cutoff would read as `null`. */
const unknown = bundle.filter(der => !known.has(derKey(der)));
if (unknown.length > 0) {
  throw new Error(
    `${unknown.length} of ${bundle.length} roots in cacert.pem are absent from certdata.txt.\n` +
      `The two pins disagree about what NSS contains — cacert ${CACERT_SHA256.slice(0, 12)}, ` +
      `nss ${CERTDATA_COMMIT.slice(0, 12)}. Re-pin them together rather than shipping cutoffs\n` +
      'read from a file that does not describe these roots.',
  );
}

const entries = indexAnchors(
  bundle.map((der, index) => ({
    id: `cacert.pem#${index}`,
    der,
    serverDistrustAfter: distrust.get(derKey(der))?.notAfter ?? null,
  })),
);

/** Unlike `indexAnchors`, a certificate that does not decode fails the build rather than shrinking the store. */
if (entries.length !== bundle.length) {
  throw new Error(
    `${bundle.length - entries.length} of ${bundle.length} roots in cacert.pem did not decode.\n` +
      'Refusing to ship a trust store smaller than its input — find out which, and why.',
  );
}

const withCutoff = entries.filter(entry => entry.serverDistrustAfter !== null);
const base64 = (bytes: Uint8Array): string => Buffer.from(bytes).toString('base64');

writeFileSync(
  ARTIFACT,
  `${[
    '/**',
    ' * GENERATED by `pnpm -F @yozz.app/x509 anchors:build`. Do not edit.',
    ' *',
    ` * curl cacert.pem  sha256 ${sha256(Buffer.from(cacert, 'utf8'))}`,
    ` * NSS certdata.txt commit ${CERTDATA_COMMIT}`,
    ` * NSS certdata.txt sha256 ${sha256(Buffer.from(certdata, 'utf8'))}`,
    ' *',
    ` * ${entries.length} roots, ${withCutoff.length} carrying a server distrust-after cutoff.`,
    ' * A cutoff is compared against the LEAF’s notBefore, so a root past it still',
    ' * anchors everything it signed before it. See anchors/certdata.ts.',
    ' */',
    "import type { AnchorIndexEntry } from './anchors.ts';",
    '',
    'const decode = (base64: string): Uint8Array =>',
    '  Uint8Array.from(atob(base64), character => character.charCodeAt(0));',
    '',
    'export const ROOT_BUNDLE: readonly AnchorIndexEntry[] = [',
    ...entries.map(entry =>
      [
        '  {',
        `    id: ${JSON.stringify(entry.id)},`,
        `    der: decode(${JSON.stringify(base64(entry.der))}),`,
        `    subjectDer: decode(${JSON.stringify(base64(entry.subjectDer))}),`,
        `    serverDistrustAfter: ${
          entry.serverDistrustAfter === null
            ? 'null'
            : `new Date(${JSON.stringify(entry.serverDistrustAfter.toISOString())})`
        },`,
        '  },',
      ].join('\n'),
    ),
    '];',
  ].join('\n')}\n`,
);

console.log(`${entries.length} roots -> ${ARTIFACT}`);
for (const entry of withCutoff) {
  const label = distrust.get(derKey(entry.der))?.label ?? entry.id;
  console.log(
    `  distrust-after ${entry.serverDistrustAfter?.toISOString().slice(0, 10)}  ${label}`,
  );
}
